name:          "WTF, HTML and CSS?"
url:           http://mathieuhays.github.io/wtf-html-css/
repo:          https://github.com/mathieuhays/wtf-html-css
twitter:       https://twitter.com/mathieuhays

markdown:      redcarpet
permalink:     pretty
pygments:      true
